### PR TITLE
Btsimonh master dev

### PR DESCRIPTION
**Pull request by btsimonh**
Hi steve(?),
I've added Async operation to Matrix operations convertGrayscale() and resize():

If called normally, they are synchronous.
if called like:
img.convertGrayscale(function(err, res){}); - err is null/string, res is 0/1.
img.resize(function(err, resized_image), {width:w, height:h}); - err is null/string, resized_image is result.
then the function will run async on a separate thread.

### CODE REVIEW

**Comment by ssttevee** [comment]
Thanks for the PR. I actually started rewriting this library from scratch for opencv v3.3.0 on the [akshonesports/node-opencv#3.x](https://github.com/akshonesports/node-opencv/tree/3.x) branch with a subjectively better and more idiomatic interface than the original.

Since your changes are for my modifications to the original library, I suggest that you open a PR to the original repo.

Feel free to revise your changes for the 3.3.0 rewrite though. I will change the default branch so nobody else gets confused.

**Comment by btsimonh** [comment]
did you see my email - maybe we can discuss collaboration there?

**Comment by ssttevee** [comment]
I definitely don't mind collaborating, but I don't think I got your email.

**Comment by ssttevee** [comment]
I guess I'll merge it into master anyways

**Comment by btsimonh** [comment]
oh, sent to to the mail address in the git repo commits....

Anyway; I was going to ask what lead to the major changes in the first commit after the fork....  There's quite a lot changed, and I'm not sure how much effect this will have on my code when I revert to peter's master.  

also see here https://github.com/peterbraden/node-opencv/issues/563#issuecomment-340782771 - there is a repo I found which you may find interesting (https://github.com/justadudewhohacks/opencv4nodejs); doing something like you.

**Pull request merged**
